apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  FOO: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wordpress-mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-mariadb
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-mariadb
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: wordpress
        app.kubernetes.io/version: v10.3.32
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3.32
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: ddls
      volumes:
        - name: ddl
          configMap:
            name:
