apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  MARIADB_DATABASE: test
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
stringData:
  MARIADB_ROOT_PASSWORD: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
data:
  initdb.sql: |
    CREATE TABLE foo (bar VARCHAR(12), baz VARCHAR(12));
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wordpress-mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-mariadb
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-mariadb
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: wordpress
        app.kubernetes.io/version: v10.3.32
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3.32
        envFrom:
        - configMapRef:
            name: mariadb-config
        - secretRef:
            name: mariadb-secret
        volumeMounts:
        - name: mariadb-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-initdb
        configMap:
          name: mariadb-initdb
