apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster
spec:
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posgres
  serviceName: postgres-cluster
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest

