apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  MARIADB_DATABASE: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
stringData:
  MARIADB_ROOT_PASSWORD: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
data: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
    targetPort: mysql
    name: mysql
  selector:
    app.kubernetes.io/name: wordpress-mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: wordpress-mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
  name: mariadb
spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-mariadb
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-mariadb
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: wordpress
        app.kubernetes.io/version: v10.3.32
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3.32
        envFrom:
        - configMapRef:
            name: mariadb-config
        - secretRef:
            name: mariadb-secret
        volumeMounts:
        - name: mariadb-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: tmp
          mountPath: /tmp
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: mariadb-initdb
        configMap:
          name: mariadb-initdb
