---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    foo: bar
    unwichtiger-pod: "true"
    documentation: |
      Ich kann auch ganz einfach mehrere Zeilen Code hier reinschreiben, wenn ich möchte.
      Ist das nicht super?

      sdfsdfs

      sdfsdf
  labels:
    foo: bar
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: a
  name: nginx-a
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    foo: bar
    unwichtiger-pod: "true"
  labels:
    foo: bar
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: b
  name: nginx-b
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
