---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: kube-system
  labels:
    app: promtail
    group: grafana
spec:
  selector:
    matchLabels:
      app: promtail
      group: grafana
  template:
    metadata:
      labels:
        app: promtail
        group: grafana
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:make-images-static-26a87c9
        imagePullPolicy: Always
        args: ["-config.file=/etc/promtail/promtail-config.yaml"]
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
